export const CHAT_ABORT_FLAG_TTL_SECONDS = 300;
export const CHAT_ABORT_POLL_INTERVAL_MS = 500;
export const CHAT_TITLE_MAX_LENGTH = 80;
export const CHAT_DELETION_TOMBSTONE_TTL_SECONDS = 60 * 60 * 24 * 7;
export const CHAT_PREVIEW_SAVE_TIMEOUT_MS = 30_000;
export const CHAT_LINKEDIN_PREVIEW_TRUNCATION_LIMIT = 800;
export const CHAT_INTEGRATIONS_CACHE_TTL_SECONDS = 300;
