import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { changelog } from "@/../.source/server";
import { getMDXComponents } from "@/../mdx-components";
import { NotraMark } from "@/components/notra-mark";
import { TableOfContents } from "@/components/table-of-contents";
import { formatChangelogDate } from "@/utils/changelog";
import { DEFAULT_SOCIAL_IMAGE, TWITTER_HANDLE } from "@/utils/metadata";
import {
  getShowcaseCompany,
  getShowcaseEntrySlug,
  SHOWCASE_COMPANIES,
} from "@/utils/showcase";
import { SITE_URL } from "@/utils/urls";
import type { ShowcaseEntryPageProps } from "~types/showcase";

export function generateStaticParams() {
  return SHOWCASE_COMPANIES.flatMap((company) =>
    changelog
      .filter((entry) => entry.info.path.startsWith(`${company.slug}/`))
      .map((entry) => ({
        name: company.slug,
        slug: getShowcaseEntrySlug(entry.info.path),
      }))
  );
}

export async function generateMetadata({
  params,
}: ShowcaseEntryPageProps): Promise<Metadata> {
  const { name, slug } = await params;
  const entry = changelog.find(
    (item) => item.info.path === `${name}/${slug}.mdx`
  );

  if (!entry) {
    return {};
  }

  const url = `${SITE_URL}/changelog/${name}/${slug}`;

  return {
    title: { absolute: entry.title },
    description: entry.description,
    alternates: { canonical: url },
    openGraph: {
      title: entry.title,
      description: entry.description,
      url,
      type: "article",
      publishedTime: entry.date,
      siteName: "Notra",
      images: [DEFAULT_SOCIAL_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: entry.title,
      description: entry.description,
      images: [DEFAULT_SOCIAL_IMAGE.url],
      site: TWITTER_HANDLE,
      creator: TWITTER_HANDLE,
    },
  };
}

export default async function ShowcaseEntryPage({
  params,
}: ShowcaseEntryPageProps) {
  const { name, slug } = await params;
  const company = getShowcaseCompany(name);
  const entry = changelog.find(
    (item) => item.info.path === `${name}/${slug}.mdx`
  );

  if (!company || !entry) {
    notFound();
  }

  const MDX = entry.body;

  return (
    <div className="w-full max-w-[760px] self-center">
      <Link
        className="mb-6 inline-flex items-center gap-1 font-sans text-foreground/50 text-sm transition-colors hover:text-foreground"
        href={`/changelog/${name}`}
      >
        &larr; {company.name}
      </Link>

      <h1 className="font-sans font-semibold text-3xl tracking-tight sm:text-4xl">
        {entry.title}
      </h1>
      <time className="mt-2 block font-sans text-foreground/40 text-sm">
        {formatChangelogDate(entry.date)}
      </time>

      <div className="mt-4 flex items-center gap-1.5">
        <span className="text-primary">
          <NotraMark className="size-3.5 shrink-0" />
        </span>
        <p className="font-sans text-muted-foreground text-xs">
          This changelog is generated by Notra for demonstration purposes. Notra
          is not affiliated with {company.name}.
        </p>
      </div>

      <article className="prose prose-neutral dark:prose-invert mt-8 max-w-none prose-headings:font-sans prose-headings:font-semibold prose-p:font-sans prose-a:text-primary prose-li:text-foreground/80 prose-p:text-foreground/80 prose-strong:text-foreground prose-p:leading-7 prose-headings:tracking-tight prose-a:no-underline hover:prose-a:underline">
        <TableOfContents toc={entry.toc} />
        <MDX components={getMDXComponents()} />
      </article>

      <div className="mt-12 flex items-center gap-2">
        <Link
          className="flex items-center gap-2 text-muted-foreground transition-colors hover:text-foreground"
          href={`/?utm_source=showcase&utm_medium=referral&utm_campaign=${name}`}
        >
          <span className="text-primary">
            <NotraMark className="size-4 shrink-0" />
          </span>
          <span className="font-medium font-sans text-xs">
            Powered by Notra
          </span>
        </Link>
      </div>
    </div>
  );
}
